- name: variables in ansible 
  hosts: mongodb
  vars:
    COURSE: JAVA
    TRAINER: VISHU
    DURATION: 110HRS
  tasks:
  -name: Devos with AWS
    ansible.builtin.debug:
      msg: "Hello I am learning ansible"
  -name: print variables
    ansible.builtin.debug:
      msg: "Hello, I am learning Detgails {{COURSE}}, and {{TRAINER}}, and {{DURATION}}"

# - name: variables in ansible
#   hosts: mongodb
#   # This is Play level variables, map
#   vars:
#     COURSE: DevOps with AWS
#     TRAINER: Sivakumar
#     DURATION: 110HRS
#   tasks:
#   - name: print hello world
#     ansible.builtin.debug:
#       msg: "Hello, I am learning Ansible"
#   - name: print variables
#     ansible.builtin.debug:
#       msg: "Hello, I am learning {{COURSE}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}"

