- name: varibales from files
  hosts: mongodb
  vars_files:
  - variables.yaml
  tasks:
  - name: printing variables
      ansible.builtin.debug:
        msg: "We are learning {{NAME}}, Duration is: {{DURATION}}"


# - name: variables from files
#   hosts: localhost #managing the ansible server itself
#   vars_files:
#   - variables.yaml
#   tasks:
#   - name: printing variables
#     ansible.builtin.debug:
#       msg: "We are learning {{NAME}}, Duration is: {{DURATION}}, Trainer is: {{TRAINER}}"