- name: loops
  hosts: localhost
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{item}}"
    loop:
    - shiva
    - vishwa
    - abcd


# - name: loops example
#   hosts: localhost # you no need to give user name and password through ansible command line
#   tasks:
#   - name: print the names
#     ansible.builtin.debug:
#       msg: "Hello {{item}}"
#     loop:
#     - Sivakumar
#     - Raheem
#     - John